# Generated by Django 4.1.7 on 2023-03-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedpasswords',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='storedpasswords',
            name='description',
            field=models.TextField(),
        ),
    ]
