# Generated by Django 4.1.7 on 2023-03-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0002_storedpasswords_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedpasswords',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
