# Generated by Django 4.1.8 on 2023-04-20 19:54

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0007_alter_password_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='pass_word',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='password',
            name='user_name',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
